### ISSUE TITLE
Allow multiple configuration environments

### ISSUE THREAD

**Issue by alexander-jackson** [Sybl-ml/dodona#45]
Environment variables are currently loaded directly from the `.env` file in all cases, whether we are running unit tests, developing the server or in future running in production. This could lead to issues, as the tests currently delete everything in the database to add its own data.

Instead, we could use a tiered system of environments, allowing more fine-grained control over the configuration. This would be similar to Rocket's `Rocket.toml` file (as per [https://rocket.rs/v0.4/guide/configuration/#rockettoml](here)). This allows for a general `global` configuration, with other configs being able to overwrite the defaults.

This, for example, would allow a `testing` section to use a local MongoDB instance and a lower amount of PBKDF2 iterations, whereas the `production` environment could use the Atlas instance with a more security focused round number. A sample configuration file is as follows:

```toml
[global]
pbkdf2_iterations = 10000
pepper = "something"
conn_str = "<atlas instance>"

[test]
pbkdf2_iterations = 100
conn_str = "mongodb://localhost:27017"
```

Then, when running unit tests, we inherit everything from `global` that is not overwritten in the `test` section.
